version: "3.9"

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    networks:
      - default-net
  app:
    build:
      context: .
      target: app
    image: myugen/kotlin-spring-boilerplate:latest
    container_name: kotlin-spring-boilerplate_app
    env_file:
      - .env
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default-net

networks:
  default-net:
    driver: bridge